<?php include_once "head.phtml" ?>
<a href="<?php echo App::config("url") ?>oglas/prepareadd" class="success button expanded">
    Dodaj novi oglasa
</a>
<table>
    <thead>
        <tr>
            <th>Naziv</th>
            <th>Opis oglasa</th>
            <th>Datum oglasa</th>
            <th>Slika</th>
            <th>Osoba</th>
            <th>Aktivan</th>
            <th>Akcija</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($oglas as $oglas): ?>
        <tr>
            <td><?php echo $oglas->naziv ?></td>
            <td><?php echo $oglas->opis ?></td>
            <td><?php echo $oglas->datumOglasa ?></td>
            <td><?php echo $oglas->slika ?></td>
            <td><?php echo $oglas->osoba_ime ?></td>
            <td>
            <i class="fa<?php echo $oglas->aktivan ? "s" : "r" ?> fa-check-square"></i>
            </td>           

            <td> 
                <a href="<?php echo App::config("url") ?>oglas/prepareedit/<?php echo $oglas->sifra ?>">
                    <i style ="color:green;" class="fas fa-edit fa-2x"></i>
                </a>

                <?php if($oglas->ukupno==0): ?>
                    <a style="color: red;"
                     href="<?php echo App::config("url") ?>oglas/delete/<?php echo $oglas->sifra ?>">
                        <i class="fas fa-trash fa-2x"></i>
                    </a>
                <?php endif; ?>
            
             </td>
        </tr>
        <?php endforeach;?>
    </tbody>
</table>