<br>
<br>
<br>
<div class="ui main text container segment">
    <div class="ui huge header">New <?php echo App::config("nazivApp") ?></div>
    <!-- <form class="ui form" action="<?php echo App::config("url") ?>oglas/edit/<?php echo Request::post("sifra") ?>" method="POST"> -->
    <form class="ui form" method="post" 
action="<?php echo App::config("url") ?>vrsta/add/<?php echo Request::post("sifra") ?>">

        <div class="field">
            <label>Vrsta</label>
            <input type="text" name="vrsta" 
    value="<?php echo Request::post("vrsta") ?>" />
        </div>

        <div class="field">
        <label>Veličina</label>
        <input type="text" name="velicina"
    value="<?php echo Request::post("velicina") ?>" />
        </div>
        

        <!-- <input class="ui violet big basic button" type="submit"> -->
        <div class="ui buttons">
  <a href="<?php echo App::config("url") ?>vrsta/index"><div class="ui button"></i>Odustani</div></a>
  <div class="or"></div>
  <input type="submit" class="ui positive button" value="Dodaj" />
    </form>
    <?php echo $poruka ?>
</div>

