<br>
<br>
<table class="ui celled table">
<a href="<?php echo App::config("url") ?>pas/prepareadd">

  <thead>
    <tr>
    <th>Ime</th>
    <th>Slika</th>
    <th>Vrsta</th>
    <th>Akcija</th>
  </tr>
  </thead>
  <tbody>
  <?php foreach($pas as $pas): ?>

    <tr>
    <td><?php echo $pas->ime ?></td>
    <td id="slikaPas"><img src="<?php echo $pas->slika ?>" /></td>
    <td><?php echo $pas->pas_vrsta ?></td>
    <td> 
    <a href="<?php echo App::config("url") ?>pas/prepareedit/<?php echo $pas->sifra ?>">
        <i style ="color:green;" class="fas fa-edit fa-2x"></i>
    </a>

    <?php if($pas->ukupno==0): ?>
        <a style="color: red;"
            href="<?php echo App::config("url") ?>pas/delete/<?php echo $pas->sifra ?>">
            <i class="fas fa-trash fa-2x"></i>
        </a>
    <?php endif; ?>   
    </td> 
</tr>
    <?php endforeach;?>
    
  </tbody>
  <tfoot class="full-width">
    <tr>
      <th colspan="4">
      <div class="positive ui button" style="float: right;">
      <a href="<?php echo App::config("url") ?>pas/prepareadd"><div class="ui green button"><i class="paw icon"></i></i>Dodaj</div></a>
    </div>
      </th>
    </tr>
  </tfoot>
</table>
