<br>
<br>
<br>
<div class="ui main text container segment">
    <div class="ui huge header">New <?php echo App::config("nazivApp") ?></div>
    <form class="ui form" method="post" 
action="<?php echo App::config("url") ?>pas/add/<?php echo Request::post("sifra") ?>">

        <div class="field">
            <label>Ime</label>
            <input type="text" name="ime" 
    value="<?php echo Request::post("ime") ?>" />
        </div>

        <div class="field">
        <label>Slika</label>
        <input type="text" name="slika"
    value="<?php echo Request::post("slika") ?>" />
        </div>
        
        <!-- <div class="field">
        <label>Vrsta</label>
        <input type="number" name="vrsta"
    value="<?php echo Request::post("vrsta") ?>" />
        </div>
         -->
        <div class="field">
    <label for="vrsta">Vrsta</label>
<select name="vrsta" id="vrsta">
    <option value="0">Choose</option>

    <?php foreach(Vrsta::read() as $vrsta): ?>

        <option

            <?php if(Request::post("vrsta") == $vrsta->sifra):?>
                selected="selected"
            <?php endif;?>

                value="<?php echo $vrsta->sifra ?>"><?php echo $vrsta->vrsta ?></option>
                <?php endforeach; ?>
</select>

</div>

        
    <div class="ui buttons">
  <a href="<?php echo App::config("url") ?>pas/index"><div class="ui button"></i>Odustani</div></a>
  <div class="or"></div>
  <input type="submit" class="ui positive button" value="Dodaj" />

</div>
    </form>
    <?php echo $poruka ?>
</div>



<!-- <label for="vrsta">Vrsta</label>
<select name="vrsta" id="vrsta">
    <option value="0">Choose</option>

    <?php foreach(Vrsta::read() as $vrsta): ?>

        <option

            <?php if(Request::post("vrsta") == $vrsta->id):?>
                selected="selected"
            <?php endif;?>

                value="<?php echo $vrsta->id ?>"><?php echo $vrsta->vrsta ?></option>

    <?php endforeach; ?>

</select> -->
