<a href="<?php echo App::config("url") ?>osoba/prepareadd" class="success button expanded">
    Dodaj novu osobu
</a>
<table>
    <thead>
        <tr>
            <th>Ime</th>
            <th>Prezime</th>
            <th>Email</th>
            <th>Adresa</th>
            <th>Mobitel</th>
            <th>Slika</th>
            <th>Pas</th>
            <th>Akcija</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($osoba as $osoba): ?>
        <tr>
            <td><?php echo $osoba->ime ?></td>
            <td><?php echo $osoba->prezime ?></td>
            <td><?php echo $osoba->email ?></td>
            <td><?php echo $osoba->adresa ?></td>
            <td><?php echo $osoba->mobitel ?></td>
            <td id="slikaPas"><img src="<?php echo $osoba->slika ?>" /></td>
            <td><?php echo $osoba->pas_ime ?></td>

<!--            <td>-->
<!--            -->
<!--            <i class="fa--><?php //echo $smjer->verificiran ? "s" : "r" ?><!-- fa-check-square"></i>-->
<!--            -->
<!--            </td>-->
            <td> 
                <a href="<?php echo App::config("url") ?>osoba/prepareedit/<?php echo $osoba->sifra ?>">
                    <i style ="color:green;" class="fas fa-edit fa-2x"></i>
                </a>

                <?php if($osoba->ukupno==0): ?>
                    <a style="color: red;"
                     href="<?php echo App::config("url") ?>osoba/delete/<?php echo $osoba->sifra ?>">
                        <i class="fas fa-trash fa-2x"></i>
                    </a>
                <?php endif; ?>
            
             </td>
        </tr>
        <?php endforeach;?>
    </tbody>
</table>