<label>Naziv
    <input type="text" name="naziv" 
    value="<?php echo Request::post("naziv") ?>" />
  </label>

  <label>Trajanje
    <input type="number" name="trajanje"
    value="<?php echo Request::post("trajanje") ?>" />
  </label>

  <label>Cijena
    <input type="number" step="0.01" name="cijena"
    value="<?php echo Request::post("cijena") ?>" />
  </label>

  <label>Upisnina
    <input type="number" step="0.01" name="upisnina"
    value="<?php echo Request::post("upisnina") ?>" />
  </label>

  <label>Verificiran
    <input type="checkbox" name="verificiran" 
    <?php if(Request::post("verificiran")==="on"){
        echo "checked";
    } ?>
     />
  </label>