<label>Ime
    <input type="text" name="ime" 
    value="<?php echo Request::post("ime") ?>" />
  </label>

  <label>Prezime
    <input type="text" name="prezime"
    value="<?php echo Request::post("prezime") ?>" />
  </label>

  <label>Email
    <input type="text" name="email"
    value="<?php echo Request::post("email") ?>" />
  </label>

  <label>Adresa
    <input type="text" name="adresa"
    value="<?php echo Request::post("adresa") ?>" />
  </label>

  <label>Mobitel
    <input type="number" name="mobitel"
    value="<?php echo Request::post("mobitel") ?>" />
  </label>

  <label>Slika
    <input type="text" name="slika"
    value="<?php echo Request::post("slika") ?>" />
  </label>

  <label>Pas
    <input type="number" name="pas"
    value="<?php echo Request::post("pas") ?>" />
  </label>