<a href="<?php echo App::config("url") ?>smjer/prepareadd" class="success button expanded">
    Dodaj novi smjer
</a>
<table>
    <thead>
        <tr>
            <th>Naziv</th>
            <th>Trajanje</th>
            <th>Cijena</th>
            <th>Upisnina</th>
            <th>Verificiran</th>
            <th>Akcija</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($smjerovi as $smjer): ?>
        <tr>
            <td><?php echo $smjer->naziv ?></td>
            <td><?php echo $smjer->trajanje ?></td>
            <td><?php echo $smjer->cijena ?></td>
            <td><?php echo $smjer->upisnina ?></td>
            <td>
            
            <i class="fa<?php echo $smjer->verificiran ? "s" : "r" ?> fa-check-square"></i>
            
            </td>
            <td> 
                <a href="<?php echo App::config("url") ?>smjer/prepareedit/<?php echo $smjer->sifra ?>">
                    <i class="fas fa-edit fa-2x"></i>
                </a>

                <?php if($smjer->ukupno==0): ?>
                    <a style="color: red;"
                     href="<?php echo App::config("url") ?>smjer/delete/<?php echo $smjer->sifra ?>">
                        <i class="fas fa-trash fa-2x"></i>
                    </a>
                <?php endif; ?>
            
             </td>
        </tr>
        <?php endforeach;?>
    </tbody>
</table>