<html>
    <head>
        <title>Blog App</title>
        <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.css">
        <link rel="stylesheet" type="text/css" href="/stylesheets/app.css">

    </head>
    
    <body>
        
        <div class="ui fixed inverted menu">
            <div class="ui container">
                <div  class="header item"><i class="paw icon"></i><?php echo App::config("nazivApp") ?></div>
                <a href="/" class="item"><i style="font-size:160%;" class="fas fa-home"></i></a>
                <a class="item" href="<?php echo App::config("url")."onama" ?>">O nama</a>
                <?php if(Session::getInstance()->isLogiran()): ?>

                <a  class="item" href="<?php echo App::config("url")."osoba/index" ?>">Osoba</a>
                <a  class="item" href="<?php echo App::config("url")."pas/index" ?>">Pas</a>
                <a  class="item" href="<?php echo App::config("url")."vrsta/index" ?>">Vrsta</a>
                <a  class="item" href="<?php echo App::config("url")."oglas/index" ?>">Oglas</a>
                <a  class="item" href="<?php echo App::config("url")."operater/index" ?>">Operateri</a>
                <?php endif; ?>

                <div class="right menu">
                        <?php if(Session::getInstance()->isLogiran()): ?>
                        <a class="item" href="<?php echo App::config("url") ?>admin/odjava">Odjava
                            <?php echo Session::getInstance()->getUser()->imePrezime ?>
                        </a>
                        <?php else:?>
                        <a class="item"  href="<?php echo App::config("url") ?>admin/registration">Registracija</a>

                        <a class="item" href="<?php echo App::config("url") ?>admin/prijava">Prijava</a>
                        <?php endif;?>
                </div>
            </div>
        </div>