<!doctype html>
<html class="no-js" lang="en" dir="ltr">
  <head>
    <?php include_once "head.phtml" ?>
  </head>
  <body>
  <?php include_once "izbornik.phtml" ?>

    <div class="grid-container">

    <div class="grid-x">

        <div id="content" class="large-11 medium-11 small-12 columns">
            <h1 style="width: 100%; text-align: center; padding-top:15px;"><?php echo App::config("nazivApp") ?></h1>
        </div>
    </div>
       
        <div class="content1">
            <h3 style="text-align: center; font-size: 1.5rem">If you are bored and don't know where to go<br> come here and Walk My Doggy Dog!</h3>
            <hr>
            <div>
                <br>
            <img id="DoggyImg" style="" src="<?php echo App::config("url") ?>public/img/walking-dogs-clipart-7.png" alt="Image" width="640" height="427" />

        </div>
            <div class="" style="min-height: 400px;">
                <?php echo $content ?>

            </div>


        <div class="">
           &copy; Matej Sokol <?php echo date("Y") ?>
        </div>
        </div>
    </div>
    <script src="<?php echo App::config("url") ?>public/js/vendor/jquery.js"></script>
    <script src="<?php echo App::config("url") ?>public/js/vendor/what-input.js"></script>
    <script src="<?php echo App::config("url") ?>public/js/vendor/foundation.js"></script>
    <script src="<?php echo App::config("url") ?>public/js/app.js"></script>
  </body>
</html>