<?php 
  
 $js="
 <script src=\"https://code.highcharts.com/highcharts.js\"></script>
<script src=\"https://code.highcharts.com/modules/exporting.js\"></script>
<script src=\"https://code.highcharts.com/modules/export-data.js\"></script>
<script>var podaci = " . $podaci . ";</script>
<script src=\"" . APP::config("url") . "public/js/nadzornaPloca.js\"></script>
 ";
?>


<div id="container" style="min-width: 310px; height: 400px; max-width: 600px; margin: 0 auto"></div>