<br>
<br>
<br>

<form class="log-in-form" method="post"
      action="<?php echo App::config("url") ?>admin/register">
<div class="ui main text container segment">
    <div class="ui huge header">Registracija <?php echo App::config("nazivApp") ?></div>
    
        <div class="field">
            <label>Ime</label>
            <input type="text" name="ime" placeholder="Ime" required>
        </div>

        <div class="field">
            <label>Prezime</label>
            <input type="text" name="prezime" placeholder="Prezime" required>
        </div>

        <div class="field">
            <label>Email</label>
            <input type="email" name="email" placeholder="Email" required>
        </div>

        <div class="field">

            <label>Password</label>
            <input type="password" name="password"  placeholder="Password" required>
        </div>

  <button type="submit" name="register_button" class="ui primary basic button" value="Register">Register</button>

</div>

</form>
<?php echo $poruka ?>