<html>
    <head>
        <title><?php echo App::config("nazivApp") ?></title>
        <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.css">
        <link rel="stylesheet" type="text/css" href="<?php echo App::config("url") ?>public/stylesheets/app.css">

    </head>
    
    <body>
        
        <div class="ui fixed inverted menu">
            <div class="ui container">
                <div  class="header item"><i class="paw icon"></i><?php echo App::config("nazivApp") ?></div>
                <a href="/" class="item"><i style="font-size:160%;" class="fas fa-home"></i></a>
                <a href="<?php echo App::config("url") ?>oglas/add" class="item">Novi oglas</a>

            </div>
        </div><div class="ui main text container segment">
        <?php foreach($oglas as $oglas): ?>

    <div class="ui huge header"><?php echo $oglas->naziv ?></div>
    <div class="ui top attached ">
        <div class="item">
            <img class="ui centered rounded image" src="<?php echo /* TODO: urlencode */ $oglas->slika ?>" >
            <br>
            <div class="description">
                <p><i style="color: green;" class="fas fa-user"></i> <?php echo $oglas->osoba_ime ?></p>
            </div>
            <div class="description">
                <p><i style="color: green;" class="fas fa-mobile-alt"></i> <?php echo $oglas->osoba_mobitel ?></p>
            </div>
            <div class="content">
                <span><i style="color: green;" class="fas fa-calendar-alt"></i><?php echo date("d-m-Y", strtotime($oglas->datumOglasa)); ?></span>
           
            </div>
            <div class="description">
            <p><i style="color: green;" class="fa<?php echo $oglas->aktivan ? "s" : "r" ?> fa-flag"></i> Oglas <?php echo $oglas->aktivan ? "" : "ne" ?>aktivan</p>            
            </div>
            <div class="description">
                <p><?php echo $oglas->opis ?></p>
            </div>
            <br>
            <a class="ui orange basic button" href="<?php echo App::config("url") ?>oglas/prepareedit/<?php echo $oglas->sifra ?>"><i style="font-size:160%;" class="fas fa-user-edit"></i></a>
            <?php if($oglas->ukupno==0): ?>
            <form id="delete" action="<?php echo App::config("url") ?>oglas/delete/<?php echo $oglas->sifra ?>" method="POST">
                <button class="ui red basic button"><i style="font-size:160%;" class="fas fa-minus-circle"></i></button>
            </form>
            <?php endif; ?>

        </div>
    </div>
    
    <?php endforeach;?>
    <nav aria-label="">
  <ul class="pagination text-center">
    <li style="font-size: 2em;" class=""><a href="<?php echo App::config("url") ?>oglas/index/<?php echo $prethodna ?>" aria-label="Next page"><i style="color:gray;" class="fas fa-arrow-left"></i> <span class="show-for-sr">page</span></a></li>
    <li style="font-size: 2em;" class=""><a href="<?php echo App::config("url") ?>oglas/index/<?php echo $sljedeca ?>" aria-label="Next page"><i style="color:gray;" class="fas fa-arrow-right"></i> <span class="show-for-sr">page</span></a></li>
  </ul>
</nav>

</div>
</body>
</html>