<label>Naziv
    <input type="text" name="naziv" 
    value="<?php echo Request::post("naziv") ?>" />
  </label>

  <label>Datum oglasa
    <input type="text" name="datumOglasa"
    value="<?php echo Request::post("datumOglasa") ?>" />
  </label>

  <label>Slika
    <input type="text" name="slika"
    value="<?php echo Request::post("slika") ?>" />
  </label>
  <label>Aktivan
    <input type="checkbox" name="aktivan" 
    <?php if(Request::post("aktivan")==="on"){
        echo "checked";
    } ?> />
    </label>
    <label>Osoba
    <input type="number" name="osoba"
    value="<?php echo Request::post("osoba") ?>" />
  </label>
